# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application Build Preview

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
        
    - name: run Build
      run: |
        pyinstaller -F main.py

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: "KPD-The Latest for Linux"
        path: dist/main
        
  build-win-latest:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
    - name: run Build
      run: |
        pyinstaller -F main.py

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: "KPD-The Latest for Windows"
        path: dist/main.exe
        
  build-win-support:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
    - name: run Build
      run: |
        pyinstaller -F main.py

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: "KPD-The Support for Windows"
        path: dist/main.exe
        
